/** Altium schematic binary record types (subset). */
export const RecordType = {
  Component: 1,
  Pin: 2,
  Label: 4,
  Bezier: 5,
  Polyline: 6,
  Polygon: 7,
  Ellipse: 8,
  PieChart: 9,
  RoundRectangle: 10,
  EllipticalArc: 11,
  Arc: 12,
  Line: 13,
  Rectangle: 14,
  PowerPort: 17,
  SheetSymbol: 22,
  SheetEntry: 23,
  NetLabel: 25,
  Bus: 26,
  Wire: 27,
  TextFrame: 28,
  Junction: 29,
  Image: 30,
  Sheet: 31,
  SheetName: 32,
  BusEntry: 33,
  Designator: 34,
  SheetFileName: 35,
  NoERC: 36,
  Hint: 37,
  ParameterSet: 38,
  Template: 39,
  Parameter: 41,
  ImplementationList: 44,
  Implementation: 45,
  ImplementationMap: 46,
  ImplementationPin: 48,
} as const;

export type RecordTypeId = (typeof RecordType)[keyof typeof RecordType];
